source:      .
destination: ./_site
exclude: ['*.less', 'node_modules']

url: https://peanutapp.github.io

name: Peanut
description: An app for sharing opinions
permalink: none

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"